#!/bin/bash

ARCH="i386"
RH_RELEASE="rhel6"
CHEF_VERSION="0.9.14"

makeself/makeself.sh buildroot chef-fat-installer-$RH_RELEASE.$ARCH.run "chef-client FAT Installer $CHEF_VERSION ($ARCH)" ./rvm-chef-install.sh
