#!/bin/bash
# Author:: Eric G. Wolfe <wolfe21@marshall.edu>
# Copyright:: Copyright (c) 2011
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ./rvm-chef-settings

chmod 700 /etc/profile.d/rvm.sh
. /etc/profile.d/rvm.sh
rvm install $RUBY_VERSION 
rvm use $RUBY_VERSION
rvm --default $RUBY_VERSION
rvm all do gem install --no-ri --no-rdoc chef net-ssh net-ssh-multi fog highline
rvm cleanup all
