#!/bin/bash
# Author:: Eric G. Wolfe <wolfe21@marshall.edu>
# Copyright:: Copyright (c) 2011
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ./rvm-chef-settings

if [ -e /etc/redhat-release ]; then
  echo -en "Installing rvm pre-requisites for RHEL/CentOS/Fedora\n"
  yum -y install gcc-c++ patch readline readline-devel zlib zlib-devel openssl-devel rsync git libxml-devel libxslt-devel

  # rsync the rvm-chef installation into place
  echo -en "Deploying rvm and chef-client config files\n"
  rsync -a ./etc/ /etc

  echo -en "Installing RedHat-style system/init scripts\n"
  cp -f $INIT_DIR/redhat/etc/init.d/chef-client /etc/init.d/chef-client

  if [ ! -f /etc/sysconfig/chef-client ]; then
    cp $INIT_DIR/redhat/etc/sysconfig/chef-client /etc/sysconfig/chef-client
  fi
  if [ ! -f /etc/logrotate.d/chef-client ]; then
    cp $INIT_DIR/redhat/etc/logrotate.d/chef-client /etc/logrotate.d/chef-client
  fi

elif [ -e /etc/debian_version ]; then
  echo -en "Installing rvm pre-requisites for Debian/Ubuntu\n"
  apt-get -y install build-essential bison openssl libreadline6 libreadline6-dev curl git-core zlib1g zlib1g-dev libssl-dev libyaml-dev libsqlite3-0 libsqlite3-dev sqlite3 libxml2-dev libxslt-dev autoconf libc6-dev ncurses-dev rsync libxml2-dev libxslt1-dev

  # rsync the rvm-chef installation into place
  echo -en "Deploying rvm and chef-client config files\n"
  rsync -a ./etc/ /etc

  echo -en "Installing Debian-style system/init scripts\n"

  cp -f $INIT_DIR/debian/etc/init.d/chef-client /etc/init.d/chef-client

  if [ ! -f /etc/init/chef-client.conf ]; then
    cp $INIT_DIR/debian/etc/init/chef-client.conf /etc/init/chef-client.conf
  fi
  if [ ! -f /etc/default/chef-client ]; then
    cp $INIT_DIR/debian/etc/default/chef-client /etc/default/chef-client
  fi

fi
