#!/bin/bash
# Author:: Eric G. Wolfe <wolfe21@marshall.edu>
# Copyright:: Copyright (c) 2011
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

. ./rvm-chef-settings

# Symlink chef-client for init script
if [ -f /usr/bin/chef-client ]; then
  echo -en "Backing up chef-client to chef-client.backup\n";
  mv /usr/bin/chef-client /usr/bin/chef-client.backup
fi

echo -en "Symlinking $CHEF_PATH/chef-client to /usr/bin\n"
ln -s $CHEF_PATH/chef-client /usr/bin/chef-client

echo
cat << "EOF"
= CHEF JUST-IN-TIME INSTALLER

Author:: Eric G. Wolfe <wolfe21@marshall.edu>
Copyright:: Copyright (c) 2011
License:: Apache License, Version 2.0

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
mitations under the License.
EOF

echo
echo -e "----------------------------------------------------------------\n"
echo -e "Additional components (RVM, Ruby, gems, and Chef) are copyright their respective authors.\n"
echo -e "This Chef application deployment is provided as-is by Eric G. Wolfe\n"
echo -e "You should be able to run chef-client -S <chef-server> after sourcing /etc/profile.d/rvm.sh\n"
