#!/usr/bin/env bash

if [[ -s "/opt/chef/environments/ruby-1.9.2-p180@global" ]] ; then
  source "/opt/chef/environments/ruby-1.9.2-p180@global"
  exec ri "$@"
else
  echo "ERROR: Missing RVM environment file: '/opt/chef/environments/ruby-1.9.2-p180@global'" >&2
  exit 1
fi
  